language: go

go:
  - 1.19.x

install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
script:
- go get -d -t -v ./...
- go build -v ./...
- go test -v ./... -covermode=count -coverprofile=coverage.out
- bash runExamples.sh